# import NOAA_request
# -*- coding: utf-8 -*-
import json
from datetime import datetime as dt

from bokeh.embed import components
from bokeh.models import DatetimeTickFormatter
from bokeh.models.tools import HoverTool
from bokeh.palettes import Spectral4
from bokeh.plotting import figure


# function included to help sort through time variables
def to_time(t):
    return dt.strptime(t, '%Y-%m-%d %H:%M')


# function to create a graph for the passed variable with each location as a new line on the graph
def create_graph(variable):
    # these files are generated by get_noaa_data() function in getAPIData.py
    data_file = open("static/api/" + variable + ".json", "r")
    var_data = json.load(data_file)
    data_file.close()

    # color coding for station locations on graphs
    color = dict(lexington=Spectral4[0], port_aransas=Spectral4[1], aransas_pass=Spectral4[2],
                 bob_hall_pier=Spectral4[3])
    # title and axis labels for each variable
    properties = {'wind_gust': ['Wind Gust', 'Time', 'Meters per Second'],
                  'wind_speed': ['Wind Speed', 'Time', 'Meters per Second'],
                  'water_level': ['Water Level', 'Time', 'Height(ft)'],
                  'air_temperature': ['Air Temperature', 'Time', 'Temperature(°F)'],
                  'water_temperature': ['Water Temperature', 'Time', 'Temperature(°F)']}

    # create a new plot with a title and axis labels
    p = figure(plot_width=650, plot_height=600, title=properties[variable][0], x_axis_label=properties[variable][1],
               y_axis_label=properties[variable][2])
    for loc in var_data:
        # skip plotting for locations that do not contain data for current variable
        if loc not in var_data:
            print loc + ' does not have var: ' + variable
            continue

        # data holders for x and y axes
        y = []
        x = []

        # sort the data based on time
        for z in sorted(var_data[loc], key=to_time):
            # skip entry if NOAA returned nothing for that time slot
            if var_data[loc][z] == "":
                continue
            y.append(var_data[loc][z])
            x.append(to_time(z))

        # add a line renderer with legend and line thickness
        p.line(x=x, y=y, legend=loc, line_width=2, line_color=color[loc])

    # Add a hover tool
    hover = HoverTool(tooltips=[(properties[variable][1], "@x{%c}"), (properties[variable][2], "@y")],
                      formatters={"x": "datetime"})
    p.add_tools(hover)

    # Make legend have functionality for click to hide location lines
    p.legend.click_policy = "hide"
    p.title.align = "center"

    # format the time display for each time range on the x-axis
    p.xaxis.formatter = DatetimeTickFormatter(
        seconds=["%m/%d %I:%M %p"],
        minsec=["%m/%d %I:%M %p"],
        minutes=["%m/%d %I:%M %p"],
        hourmin=["%m/%d %I:%M %p"],
        hours=["%a, %m/%d %I:%M %p"],
        days=["%a, %m/%d %I:%M %p"]
    )

    # save the results
    # save(p, filename="waterLvlGraph.html", title="Water Level Graph")

    # This opens the graphs in the default browser - have to import from bokeh.plotting
    # show(p)
    return p


# function to generate the graphs for each variable
def graph_generator():
    # TODO: Add a different way to visualize the wind direction in a graph or something later
    # var_list = ['wind_gust', 'wind_direction', 'wind_speed', 'water_level', 'air_temperature', 'water_temperature']
    # names of variables for which there exists a json file of data in the api/ directory
    var_list = ['wind_gust', 'wind_speed', 'water_level', 'air_temperature', 'water_temperature']
    figure_list = []
    for var in var_list:
        figure_list.append(create_graph(var))
    # function to generate js code and html dive for all the figures
    script, div_list = components(figure_list)
    return script, div_list


# graph_generator()
